# site settings
title: Dionisio
subtitle: Software
email: dionisiosoftware@gmail.com
description: Alcance o próximo nível na sua carreira em tecnologia
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dionisio.dev" # the base hostname & protocol for your site
author: "Eduardo (Dionisio) Fernandes"
street_address: 
city:
state:
zip_code:
country:
phone: +55 11 996643485

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/dionisioedu
  LinkedIn: https://www.linkedin.com/in/dionisiodev
  Twitter: https://twitter.com/dionisiodev
  Youtube: https://www.youtube.com/@dionisiodev

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
