title: Dionisio
description: Software Developer Portfolio
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Navegação principal
nav:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: Projetos
    url: /projects/
  - title: Ebooks
    url: /ebooks/
  - title: Mentoria
    url: /mentoria/
  - title: Newsletter
    url: /newsletter/
