name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para 'migration-hugo' se quiser testar antes do merge

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v3
        with:
          submodules: true  # importante se estiver usando submódulo para o tema
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.127.0'
          extended: true

      - name: Build do site
        run: hugo --minify

      - name: Deploy para a branch gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
